# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import desktop_adapter_pb2 as desktop__adapter__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in desktop_adapter_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DesktopAdapterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetActiveWindow = channel.unary_unary(
                '/desktopagent.DesktopAdapter/GetActiveWindow',
                request_serializer=desktop__adapter__pb2.Empty.SerializeToString,
                response_deserializer=desktop__adapter__pb2.WindowRef.FromString,
                _registered_method=True)
        self.ListWindows = channel.unary_unary(
                '/desktopagent.DesktopAdapter/ListWindows',
                request_serializer=desktop__adapter__pb2.Empty.SerializeToString,
                response_deserializer=desktop__adapter__pb2.WindowList.FromString,
                _registered_method=True)
        self.GetUiTree = channel.unary_unary(
                '/desktopagent.DesktopAdapter/GetUiTree',
                request_serializer=desktop__adapter__pb2.WindowRequest.SerializeToString,
                response_deserializer=desktop__adapter__pb2.UiTree.FromString,
                _registered_method=True)
        self.FindElements = channel.unary_unary(
                '/desktopagent.DesktopAdapter/FindElements',
                request_serializer=desktop__adapter__pb2.FindRequest.SerializeToString,
                response_deserializer=desktop__adapter__pb2.ElementList.FromString,
                _registered_method=True)
        self.InvokeElement = channel.unary_unary(
                '/desktopagent.DesktopAdapter/InvokeElement',
                request_serializer=desktop__adapter__pb2.ElementRequest.SerializeToString,
                response_deserializer=desktop__adapter__pb2.ActionResult.FromString,
                _registered_method=True)
        self.SetElementValue = channel.unary_unary(
                '/desktopagent.DesktopAdapter/SetElementValue',
                request_serializer=desktop__adapter__pb2.SetValueRequest.SerializeToString,
                response_deserializer=desktop__adapter__pb2.ActionResult.FromString,
                _registered_method=True)
        self.ClickPoint = channel.unary_unary(
                '/desktopagent.DesktopAdapter/ClickPoint',
                request_serializer=desktop__adapter__pb2.ClickRequest.SerializeToString,
                response_deserializer=desktop__adapter__pb2.ActionResult.FromString,
                _registered_method=True)
        self.TypeText = channel.unary_unary(
                '/desktopagent.DesktopAdapter/TypeText',
                request_serializer=desktop__adapter__pb2.TypeTextRequest.SerializeToString,
                response_deserializer=desktop__adapter__pb2.ActionResult.FromString,
                _registered_method=True)
        self.KeyCombo = channel.unary_unary(
                '/desktopagent.DesktopAdapter/KeyCombo',
                request_serializer=desktop__adapter__pb2.KeyComboRequest.SerializeToString,
                response_deserializer=desktop__adapter__pb2.ActionResult.FromString,
                _registered_method=True)
        self.OpenApp = channel.unary_unary(
                '/desktopagent.DesktopAdapter/OpenApp',
                request_serializer=desktop__adapter__pb2.OpenAppRequest.SerializeToString,
                response_deserializer=desktop__adapter__pb2.ActionResult.FromString,
                _registered_method=True)
        self.CaptureScreen = channel.unary_unary(
                '/desktopagent.DesktopAdapter/CaptureScreen',
                request_serializer=desktop__adapter__pb2.ScreenshotRequest.SerializeToString,
                response_deserializer=desktop__adapter__pb2.ScreenshotResponse.FromString,
                _registered_method=True)
        self.GetClipboard = channel.unary_unary(
                '/desktopagent.DesktopAdapter/GetClipboard',
                request_serializer=desktop__adapter__pb2.Empty.SerializeToString,
                response_deserializer=desktop__adapter__pb2.ClipboardResponse.FromString,
                _registered_method=True)
        self.SetClipboard = channel.unary_unary(
                '/desktopagent.DesktopAdapter/SetClipboard',
                request_serializer=desktop__adapter__pb2.SetClipboardRequest.SerializeToString,
                response_deserializer=desktop__adapter__pb2.ActionResult.FromString,
                _registered_method=True)
        self.Arm = channel.unary_unary(
                '/desktopagent.DesktopAdapter/Arm',
                request_serializer=desktop__adapter__pb2.ArmRequest.SerializeToString,
                response_deserializer=desktop__adapter__pb2.Status.FromString,
                _registered_method=True)
        self.Disarm = channel.unary_unary(
                '/desktopagent.DesktopAdapter/Disarm',
                request_serializer=desktop__adapter__pb2.Empty.SerializeToString,
                response_deserializer=desktop__adapter__pb2.Status.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/desktopagent.DesktopAdapter/GetStatus',
                request_serializer=desktop__adapter__pb2.Empty.SerializeToString,
                response_deserializer=desktop__adapter__pb2.Status.FromString,
                _registered_method=True)


class DesktopAdapterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetActiveWindow(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListWindows(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUiTree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindElements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InvokeElement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetElementValue(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClickPoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TypeText(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KeyCombo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CaptureScreen(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClipboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetClipboard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Arm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Disarm(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DesktopAdapterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetActiveWindow': grpc.unary_unary_rpc_method_handler(
                    servicer.GetActiveWindow,
                    request_deserializer=desktop__adapter__pb2.Empty.FromString,
                    response_serializer=desktop__adapter__pb2.WindowRef.SerializeToString,
            ),
            'ListWindows': grpc.unary_unary_rpc_method_handler(
                    servicer.ListWindows,
                    request_deserializer=desktop__adapter__pb2.Empty.FromString,
                    response_serializer=desktop__adapter__pb2.WindowList.SerializeToString,
            ),
            'GetUiTree': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUiTree,
                    request_deserializer=desktop__adapter__pb2.WindowRequest.FromString,
                    response_serializer=desktop__adapter__pb2.UiTree.SerializeToString,
            ),
            'FindElements': grpc.unary_unary_rpc_method_handler(
                    servicer.FindElements,
                    request_deserializer=desktop__adapter__pb2.FindRequest.FromString,
                    response_serializer=desktop__adapter__pb2.ElementList.SerializeToString,
            ),
            'InvokeElement': grpc.unary_unary_rpc_method_handler(
                    servicer.InvokeElement,
                    request_deserializer=desktop__adapter__pb2.ElementRequest.FromString,
                    response_serializer=desktop__adapter__pb2.ActionResult.SerializeToString,
            ),
            'SetElementValue': grpc.unary_unary_rpc_method_handler(
                    servicer.SetElementValue,
                    request_deserializer=desktop__adapter__pb2.SetValueRequest.FromString,
                    response_serializer=desktop__adapter__pb2.ActionResult.SerializeToString,
            ),
            'ClickPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.ClickPoint,
                    request_deserializer=desktop__adapter__pb2.ClickRequest.FromString,
                    response_serializer=desktop__adapter__pb2.ActionResult.SerializeToString,
            ),
            'TypeText': grpc.unary_unary_rpc_method_handler(
                    servicer.TypeText,
                    request_deserializer=desktop__adapter__pb2.TypeTextRequest.FromString,
                    response_serializer=desktop__adapter__pb2.ActionResult.SerializeToString,
            ),
            'KeyCombo': grpc.unary_unary_rpc_method_handler(
                    servicer.KeyCombo,
                    request_deserializer=desktop__adapter__pb2.KeyComboRequest.FromString,
                    response_serializer=desktop__adapter__pb2.ActionResult.SerializeToString,
            ),
            'OpenApp': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenApp,
                    request_deserializer=desktop__adapter__pb2.OpenAppRequest.FromString,
                    response_serializer=desktop__adapter__pb2.ActionResult.SerializeToString,
            ),
            'CaptureScreen': grpc.unary_unary_rpc_method_handler(
                    servicer.CaptureScreen,
                    request_deserializer=desktop__adapter__pb2.ScreenshotRequest.FromString,
                    response_serializer=desktop__adapter__pb2.ScreenshotResponse.SerializeToString,
            ),
            'GetClipboard': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClipboard,
                    request_deserializer=desktop__adapter__pb2.Empty.FromString,
                    response_serializer=desktop__adapter__pb2.ClipboardResponse.SerializeToString,
            ),
            'SetClipboard': grpc.unary_unary_rpc_method_handler(
                    servicer.SetClipboard,
                    request_deserializer=desktop__adapter__pb2.SetClipboardRequest.FromString,
                    response_serializer=desktop__adapter__pb2.ActionResult.SerializeToString,
            ),
            'Arm': grpc.unary_unary_rpc_method_handler(
                    servicer.Arm,
                    request_deserializer=desktop__adapter__pb2.ArmRequest.FromString,
                    response_serializer=desktop__adapter__pb2.Status.SerializeToString,
            ),
            'Disarm': grpc.unary_unary_rpc_method_handler(
                    servicer.Disarm,
                    request_deserializer=desktop__adapter__pb2.Empty.FromString,
                    response_serializer=desktop__adapter__pb2.Status.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=desktop__adapter__pb2.Empty.FromString,
                    response_serializer=desktop__adapter__pb2.Status.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'desktopagent.DesktopAdapter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('desktopagent.DesktopAdapter', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DesktopAdapter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetActiveWindow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktopagent.DesktopAdapter/GetActiveWindow',
            desktop__adapter__pb2.Empty.SerializeToString,
            desktop__adapter__pb2.WindowRef.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListWindows(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktopagent.DesktopAdapter/ListWindows',
            desktop__adapter__pb2.Empty.SerializeToString,
            desktop__adapter__pb2.WindowList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUiTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktopagent.DesktopAdapter/GetUiTree',
            desktop__adapter__pb2.WindowRequest.SerializeToString,
            desktop__adapter__pb2.UiTree.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FindElements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktopagent.DesktopAdapter/FindElements',
            desktop__adapter__pb2.FindRequest.SerializeToString,
            desktop__adapter__pb2.ElementList.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def InvokeElement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktopagent.DesktopAdapter/InvokeElement',
            desktop__adapter__pb2.ElementRequest.SerializeToString,
            desktop__adapter__pb2.ActionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetElementValue(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktopagent.DesktopAdapter/SetElementValue',
            desktop__adapter__pb2.SetValueRequest.SerializeToString,
            desktop__adapter__pb2.ActionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClickPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktopagent.DesktopAdapter/ClickPoint',
            desktop__adapter__pb2.ClickRequest.SerializeToString,
            desktop__adapter__pb2.ActionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TypeText(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktopagent.DesktopAdapter/TypeText',
            desktop__adapter__pb2.TypeTextRequest.SerializeToString,
            desktop__adapter__pb2.ActionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def KeyCombo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktopagent.DesktopAdapter/KeyCombo',
            desktop__adapter__pb2.KeyComboRequest.SerializeToString,
            desktop__adapter__pb2.ActionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktopagent.DesktopAdapter/OpenApp',
            desktop__adapter__pb2.OpenAppRequest.SerializeToString,
            desktop__adapter__pb2.ActionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CaptureScreen(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktopagent.DesktopAdapter/CaptureScreen',
            desktop__adapter__pb2.ScreenshotRequest.SerializeToString,
            desktop__adapter__pb2.ScreenshotResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetClipboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktopagent.DesktopAdapter/GetClipboard',
            desktop__adapter__pb2.Empty.SerializeToString,
            desktop__adapter__pb2.ClipboardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetClipboard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktopagent.DesktopAdapter/SetClipboard',
            desktop__adapter__pb2.SetClipboardRequest.SerializeToString,
            desktop__adapter__pb2.ActionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Arm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktopagent.DesktopAdapter/Arm',
            desktop__adapter__pb2.ArmRequest.SerializeToString,
            desktop__adapter__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Disarm(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktopagent.DesktopAdapter/Disarm',
            desktop__adapter__pb2.Empty.SerializeToString,
            desktop__adapter__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/desktopagent.DesktopAdapter/GetStatus',
            desktop__adapter__pb2.Empty.SerializeToString,
            desktop__adapter__pb2.Status.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
